spring:
  datasource:
    url: jdb:postgres://ec2-3-219-19-205.compute-1.amazonaws.com:5432/d3qjgt0aao5fg2
    driver-class-name: org.postgresql.Driver
    username: gasbvyyvuaveqe
    password: c17e0979d507c58ed43f1cc982d1b0b5488050597cf6c5639424affe6932efa0
  sql:
    init:
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create